apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-database-storage
  namespace: default
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi