apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- traefik-pv-claim.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- daemon-set.yaml
# - traefik-service.yaml

namespace: kube-system

commonLabels:
  app: traefik