apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-shared-storage
  namespace: default
  labels:
    app: traeifk
    tier: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi